config/routes.rb
Rails.application.routes.draw do

  get 'classrooms/index'

  resources :sales, only: [:index, :new, :create]
  resources :exchanges
  resources :deposits
  resources :withdrawals

  resources :attachments, only: [:new, :create]

  resources :courses, except: [:index, :edit, :update, :destroy], :path => "cursos" do
    resources :subjects, except: [:destroy], :path => "materia" do
      resources :lessons, except: [:destroy], :path => "aula" do
        resources :quizzes, except: [:destroy], :path => "quiz" do
          resources :questions, except: [:destroy], :path => "questao"
        end
      end
    end
  end

  resources :classrooms
  resources :questions, except: [:destroy]
  resources :user_answers, only: [:new, :create]
  resources :transictions, only: [:new, :create, :index, :show]
  resources :users, only: [:new, :create, :index] do
    resources :wallets, only: [:show], :path => "carteira"
  end
  resources :test_classes, except: [:edit, :update, :destroy, :new, :index], :path => "aula-gratis"
  get "/aula-gratis", to: "test_classes#new"
  resources :contacts, except: [:edit, :update, :destroy], :path => "contato"
  resources :blogs, except: [:destroy], :path => "blog"
  resources :dashboards, only: [:index]
  resources :tutorials
  resources :enrollments
  devise_for :users, :path => "usuario", controllers: {sessions: "sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/home'
  get '/curso/:id', to: "courses#student_show", as: :student_show
  get '/rio-de-janeiro', to: "pages#rio_de_janeiro"
  get '/seja-um-franqueado', to: "pages#franchise"
  root to: 'pages#home'

end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :subject
  belongs_to :user

  # validates :title, presence: :true
  # validates :file, presence: :true


  mount_uploader :file, PhotoUploader
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  end

end

app/models/classroom.rb
class Classroom < ApplicationRecord
  has_many :enrollments
  validates :enrollment_ids, presence: true, uniqueness: {scope: :enrollment_id, message: "usuário já matriculado"}
end

app/models/contact.rb
class Contact < ApplicationRecord
  after_create :send_welcome_email

  def send_welcome_email
    ContactMailer.contact(self).deliver_now
    ContactMailer.contact_answer(self).deliver_now
  end
end

app/models/course.rb
class Course < ApplicationRecord
  has_many  :subjects, dependent: :destroy
  mount_uploader :photo, PhotoUploader

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  end

end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
  belongs_to :classroom, optional: true
  validates :course_id, presence: true, uniqueness: {scope: :user_id, message: "usuário já matriculado"}

  def user_name
  	self.user.first_name + " " + self.user.last_name
  end

end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :user
  belongs_to :sale
 
  # before_save :change

  # def change
  # 	self.
  # end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :subject
  has_many :quizzes
  has_many :tests

  mount_uploader :file, PhotoUploader

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  end

  def next
    subject.lessons.where("id > ?", id).first
  end

  def prev
    subject.lessons.where("id < ?", id).last
  end


end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionable, polymorphic: true, optional: true
  has_many :user_answers, dependent: :destroy
  before_save :set_score

  def set_score
    if self.is_true?
      self.score = 10
    else
      self.score = 0
    end
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :lesson
  has_many :questions, as: :questionable, dependent: :destroy
  has_many :user_answers, dependent: :destroy
  accepts_nested_attributes_for :questions
end

app/models/sale.rb
class Sale < ApplicationRecord
	has_many :exchanges, dependent: :destroy
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :lessons
  belongs_to :course

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  end

end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :lesson
  has_many :questions, as: :questionable
end

app/models/test_class.rb
class TestClass < ApplicationRecord
  after_create :send_welcome_email
  belongs_to :course, optional: true

  SCHEDULE_DAYS = ['Segunda-Feira 09:00 até 10:00', 'Segunda-Feira 14:00 até 15:00', 'Segunda-Feira 17:00 até 18:00', 'Quarta-Feira 09:00 até 10:00', 'Quinta-Feira 09:00 até 10:00', 'Quinta-Feira 14:00 até 15:00', 'Quinta-Feira 17:00 até 18:00', 'Sexta-Feira 17:00 até 18:00']
  validates :schedule, inclusion: { :in => SCHEDULE_DAYS }
  validates :student, :age, :parent, :email, :phone, presence: true



  private

  def send_welcome_email
    TestClassMailer.schedule(self).deliver_now
    TestClassMailer.schedule_answer(self).deliver_now
  end

end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  belongs_to :course

  mount_uploader :file, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  attr_writer :login

  before_save :get_age, if: :age?
  before_save :set_score
  after_create :create_wallet
  has_one :wallet, dependent: :destroy
  has_many :transictions
  has_many :user_answers
  has_many :enrollments
  has_many :attachments
  has_many :deposits
  has_many :withdrawals
  mount_uploader :photo, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]

  validates :username, presence: :true, uniqueness: { case_sensitive: false }

  def user_data
    "#{self.first_name} #{self.last_name}  => #{self.login} m$#{self.wallet.money}"
  end

  def user_arrange
    User.all.order(first_name: :asc)
    "#{self.first_name} => #{self.login}"
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end


  private

  def user_age(age)
    now = Time.now.utc.to_date
    now.year - age.year - ((now.month > age.month || (
    now.month == age.month && now.day >= age.day)) ? 0 : 1)
  end

  def get_age
    self.age = user_age(self.date_of_birth)
  end

  def create_wallet
    new_wallet = Wallet.new(user_id: self.id)
    new_wallet.save
  end

  def set_score
    if self.score == 0 or self.score.nil?
      self.score = 0
    end
  end

end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
  before_save :set_money


  def set_money
    if self.money == 0 or self.money.nil?
      self.money = 0
    end
  end
end

app/models/withdrawal.rb
class Withdrawal < ApplicationRecord
  belongs_to :user
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
<% if success %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= success %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container-fluid">
    <div class="row footer p-4 p-sm-0" id="footer">
      <div class="col-sm-6 text-center">
        <div class="footer-links">
          <a href="https://www.facebook.com/moodev.com.br/" target="_blank"><i class="fab fa-facebook-f"></i></a>
          <a href="https://www.instagram.com/moodevoficial/" target="_blank"><i class="fab fa-instagram"></i></a>
          <a href="https://www.youtube.com/channel/UC7DqA7F04ffXsi3UOVf4TNQ" target="_blank"><i class="fab fa-youtube"></i></a>
        </div>
        <div class="footer-copyright">
          <small class="block"><i class="fas fa-phone"> </i> (53) 3325-0771 - Rua Senador Mendonça 120/203 - Pelotas RS<br>
          &copy; <%= Time.current.year %> MooDev. Todos os direitos reservados.</small>
        </div>
      </div>
      <div class="col-sm-6 p-2">
      <!-- ConvertKit -->
        <script src="https://f.convertkit.com/ckjs/ck.5.js"></script>
        <form action="https://app.convertkit.com/forms/986877/subscriptions" class="rounded seva-form formkit-form" method="post" data-sv-form="986877" data-uid="aaa927d885" data-format="inline" data-version="5" data-options="{&quot;settings&quot;:{&quot;after_subscribe&quot;:{&quot;action&quot;:&quot;message&quot;,&quot;redirect_url&quot;:&quot;&quot;,&quot;success_message&quot;:&quot;Enviamos um e-mail confirmando sua inscrição&quot;},&quot;return_visitor&quot;:{&quot;action&quot;:&quot;show&quot;,&quot;custom_content&quot;:&quot;&quot;},&quot;recaptcha&quot;:{&quot;enabled&quot;:false}}}" style="background-color: rgb(249, 250, 251);">
          
          <div data-style="minimal">
            <div class="formkit-header" data-element="header" style="color: rgb(77, 77, 77); font-size: 27px; font-weight: 700;">
              <h1 class="mb-0">Receba conteúdos exclusivos</h1>
            </div>
            <div class="formkit-subheader" data-element="subheader" style="color: rgb(104, 104, 104);">
              <p class="mb-0">Receber spam, você não irá!</p>
            </div>
            <div data-element="fields" data-stacked="false" class="seva-fields formkit-fields">
              <div class="formkit-field">
                <input class="formkit-input" name="email_address" required="" type="email" style="color: rgb(0, 141, 213); border-color: rgb(227, 227, 227); border-radius: 4px; font-weight: 400;" placeholder="Digite seu melhor e-mail">
              </div>
              <button data-element="submit" class="formkit-submit formkit-submit" style="color: rgb(255, 255, 255); background-color: rgb(0, 141, 213); border-radius: 4px; font-weight: 400;">
                <span>Receber</span>
              </button>
            </div>
          </div>
        </form>
      <!-- end ConvertKit -->
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="container-fluid navbar-moodev">
  <div class="row p-3">
    <div class="col-sm-12 d-flex justify-content-between align-items-center">
      <%= link_to root_path do %>
        <%= image_tag "https://res.cloudinary.com/fabiobarboza7/image/upload/moodev-weblogo-pelotas.png", class: 'logo' %>
      <% end %>
      <nav class="nav-a mx-2 d-none d-sm-block">
        <%= link_to "Home", root_path, class: "px-2"%>
        <%= link_to "Blog", blogs_path, class: "px-2"%>
        <% if request.env['PATH_INFO'] == '/'%>
          <%= link_to "Cursos", "#courses", class: "px-2"%>
        <% else %>
          <%= link_to "Cursos", root_path(:anchor => "courses"), class: "px-2"%>
        <% end %>
        <% if request.env['PATH_INFO'] == '/'%>
          <%= link_to "Contato", "#contact", class: "px-2"%>
        <% else %>
          <%= link_to "Contato", new_contact_path, class: "px-2"%>
        <% end %>
        <%#= link_to "Videos", "#videos", class: "px-2"%>
        <%= link_to "https://api.whatsapp.com/send?phone=5553984541340&text=Ol%C3%A1,%20gostaria%20de%20mais%20informa%C3%A7%C3%B5es%20sobre%20o%20curso.", class: "px-2" do %>
          Envie um WhatsApp
          <i style="color: #0EC144;" class="fab fa-whatsapp"></i>
        <% end %>
        <%= link_to aula_gratis_path, class: "text-info border-success btn btn-warning" do%>
          <span>Aula Grátis</span>
        <% end %>        
        <span class="dropdown-custom pl-3">
          <span class="btn btn-sm btn-outline-dark dropbtn" onclick="myFunction()">
            Acesso do Aluno
          </span>
          <div id="myDropdown" class="dropdown-menu dropdown-content-custom dropdown-menu-right" style="min-width: 15rem;">
            <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: "px-4 py-3 form-group"}) do |f| %>
              <% if !user_signed_in? %>
                <div class="form-inputs">
                  <%= f.input :login, required: false, autofocus: true, class: 'form-control', label: 'Login', placeholder: 'usuário ou email' %>
                  <%= f.input :password, required: false, input_html: { autocomplete: "current-password" }, class: 'form-control', label: 'Senha', placeholder: 'senha' %>
                  <%= f.input :remember_me, class: 'form-control', label: 'Lembrar senha', as: :boolean if devise_mapping.rememberable? %>
                </div>
              <% else %>
                <div class="form-inputs d-flex justify-content-between align-items-center mb-3">
                  <%= cl_image_tag(current_user.photo, class: 'avatar-mini') %>
                  <%= current_user.first_name %>
                </div>
                <div class="form-inputs">
                  <i class="fas fa-briefcase"></i>
                  <%= link_to "Dashboard", dashboards_path%>
                </div>
                <div class="form-inputs">
                  <i class="fas fa-user-edit"></i>
                  <%= link_to "Editar perfil", edit_user_registration_path(current_user)%>
                </div>
              <% end %>
              <div class="form-actions mt-3">
                <% if user_signed_in? %>
                  <%= link_to "Sair", destroy_user_session_path, class: 'btn btn-danger btn-block', method: :delete %>
                <% else %>
                  <%= f.button :submit, "Login", class: 'btn btn-primary btn-block' %>
                  <%#= render "devise/shared/links" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </span>
      </nav>
      <div class="dropdown-custom d-block d-sm-none" onclick="myFunctionXs()">
        <a class="fas fa-bars fa-2x">
        </a>
        <div id="myDropdownXs" class="dropdown-menu dropdown-content-custom dropdown-menu-right">
          <%= link_to "Home", root_path, class: "dropdown-item"%>
          <%= link_to "Blog", blogs_path, class: "dropdown-item"%>
          <%= link_to "Cursos", "#courses", class: "dropdown-item"%>
          <%#= link_to "Videos", "#videos", class: "dropdown-item"%>
          <%= link_to "Contato", "#contact", class: "dropdown-item"%>
          <%= link_to "Envie um WhatsApp", "https://api.whatsapp.com/send?phone=5553984541340&text=Ol%C3%A1,%20gostaria%20de%20mais%20informa%C3%A7%C3%B5es%20sobre%20o%20curso.", class: "px-2 dropdown-item"%>
          <%= link_to "Aula Grátis", aula_gratis_path, class: "dropdown-item text-yellow"%>
          <div class="mt-1"></div>
          <%= link_to "Acesso do Aluno", new_user_session_path, class: "dropdown-item dropdown-divider-color"%>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="horizontal-line"></div>
<div class="horizontal-line"></div>
<div class="horizontal-line"></div>

app/views/shared/_sidebar.html.erb
<nav id="sidebar">
  <div class="sidebar-header">
      <h3 class="mb-0">Area do Aluno</h3>
  </div>

  <ul class="list-unstyled components">
    <p class="text-center bg-white text-danger">
      <%= link_to "Painel Geral", dashboards_path %>
    </p>
    <li class="active">
      <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Meus cursos</a>
      <ul class="collapse list-unstyled" id="homeSubmenu">
        <% @enrollments.each do |enroll| %>
          <li>
            <%= link_to enroll.course.title, student_show_path(enroll.course) %>
          </li>
        <% end %>
      </ul>
    </li>
    <% if current_user.wallet.is_verified?  %>
      <li>
        <%= link_to user_wallet_path(current_user, current_user.wallet) do %>
          <i class="fas fa-dollar-sign text-yellow"></i>
          MooMoney Bank
        <% end %>
      </li>
    <% end %>
    <li>
      <%= link_to "Tutoriais", tutorials_path %>
    </li>
    <li>
        <%= link_to "Ranking", dashboards_path %>
    </li>
    <li>
      <%= link_to "Fale conosco", new_contact_path %>
    </li>
    <li>
      <% if policy(Enrollment).new? %>
        <%= link_to "Saques Promocionais", exchanges_path, class: "text-warning" %>
        <%= link_to "Depositar", new_deposit_path, class: "text-info" %>
        <%= link_to "Saques", new_withdrawal_path, class: "text-info" %>
        <%= link_to "Acessos", users_path, class: "text-danger" %>
        <%= link_to "Turmas", classrooms_path, class: "text-danger" %>
        <%= link_to "Cadastrar Usuário", new_user_path, class: "text-danger" %>
        <%= link_to "Cadastrar Matrícula", new_enrollment_path, class: "text-danger" %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_sidebar_bank.html.erb
<nav id="sidebar" class="bg-dark">
  <div class="sidebar-header bg-danger">
    <h6 class="mb-0"><i class="fas fa-dollar-sign text-yellow"></i> MooMoney Bank</h6>
  </div>

  <ul class="list-unstyled components">
    <li><%= link_to "Painel Geral", dashboards_path %></li>
    <li class="mb-2">
      <%= link_to user_wallet_path(current_user, current_user.wallet) do %>
        <i class="fas fa-money-bill-alt"></i> Minha Conta
      <% end %>
    </li>
    <!-- <li>
      <a href="#"><i class="fas fa-hand-holding-usd"></i> Saldo</a>
    </li>
 -->    <!-- <li>
      <a href="#"><i class="far fa-file-alt"></i> Extrato</a>
    </li> -->
    <!-- <li>
      <%#= link_to new_transiction_path do %>
      <i class="fas fa-exchange-alt"></i> Tranferência
      <%# end %>
    </li> -->
    <!-- <li>
      <%#= link_to sales_path do %>
        <i class="fas fa-money-bill-alt"></i> Comprar MooMoney
      <%# end %>
    </li> -->
    <li>
      <%= link_to "Fale conosco", new_contact_path %>
    </li>
  </ul>
</nav>

app/views/shared/_sidebar_course.html.erb
<nav id="sidebar" style="background-color: #008DD5;">
  <% if current_user.is_adult? != true %>
    <%= link_to course_subject_lessons_path(@subject.course.slug, @subject) do %>
      <div class="sidebar-header-course">
        <%= link_to course_subjects_path(@subject.course) do %>
          <div class="d-flex justify-content-between align-items-center">
            <i class="fas fa-chevron-left mr-3"></i>
            <h3 class="mb-0"><%= @subject.title %></h3>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <ul class="list-unstyled components">
    <% @lessons.each do |lesson| %>
      <li>
        <%= link_to  course_subject_lesson_path(lesson.subject.course.slug, lesson.subject.slug, lesson), remote: true do %>
          <%= lesson.title %>
          <% if lesson.quizzes.any? %>
            <% count = 0 %>
            <ul class="p-3 bg-opacity ml-2">
              <% lesson.quizzes.each do |quiz| %>
                  <li class="quiz-size d-flex justify-content-between align-items-center">
                    <span class="text-dots">Quiz - <%= quiz.title %></span>
                    <% if quiz.user_answers.where(user: current_user).any? %>
                    <% is_true = quiz.user_answers.where(user: current_user).first.is_true? ? true : false %>
                      <% if is_true %>
                        <i class="fas fa-check-circle color-lightgreen"></i>
                      <% elsif is_true == false %>
                        <i class="fas fa-times-circle color-lightred"></i>
                      <% end %>
                    <% else %>
                      <i class="fas fa-question-circle text-white"> </i>
                      <% count = count + 1 %>
                    <% end %>
                  </li>
                  <div class="lesson-horizontal-line"></div>
              <% end %>
            </ul>
            <% if count != 0 %>
              <p class="quiz-size pl-5 p-0 m-0">restam <span class="color-lightred"><%= count %></span> <%= count > 1? "Quizzes" : "Quiz" %></p>
            <% end %>
          <% end %>
        <% end %>
      </li>
      <% if current_user.admin? %>
        <%= simple_form_for [@subject.course, @subject, lesson] do |f| %>
          <%= f.input :position, label: "índice", input_html: {value: lesson.position} %>
          <%= f.submit 'Atualizar Índices', class: 'btn btn-info' %>
        <% end %>
      <% end %>
    <% end %>
    <% if current_user.admin? %>
      <div class="text-center mb-2">
        <button id="show-position" class="btn btn-info">Editar índices</button>
      </div>
    <% end %>
    <div class="horizontal-line"></div>
    <li><a>Meus Arquivos <i class="fas fa-file"></i></a></li>
    <li>
      <ul>
        <% @files.each do |file| %>
          <a class="d-flex justify-content-between align-items-center btn btn-primary" href="<%= file.file %>" download="true" target="_blank"><i class="fas fa-download"></i><%= file.title %> - Baixar</a>
        <% end %>
      </ul>
    </li>
    <div class="horizontal-line"></div>
    <li>
      <a>Salvar Arquivo</a>
      <%= simple_form_for @file, html: { class: "form-container"} do |f| %>
        <%= f.input :title, label: "Titulo", placeholder: "Digite um titulo" %>
        <%= f.input :subject_id, input_html: {value: @subject.id}, as: :hidden %>
        <label class="btn btn-warning">
          <i class="fas fa-file"></i> escolher arquivo
          <span style="display: none;">
            <%= f.input :file, label: "Arquivo" %>
          </span>
        </label>
        <div class="progress">
          <div class="progress-bar progress-bar-striped progress-bar-animated bg-warning" role="progressbar" aria-valuenow="25" aria-valuemin="espere" aria-valuemax="100"></div>
        </div>
        <%= f.submit "Salvar Arquivo", class: 'btn btn-pink mt-4' %>
      <% end %>
    </li>
    <div class="horizontal-line mt-2"></div>
    <li>
      <%= link_to "Fale conosco", new_contact_path %>
    </li>
  </ul>
</nav>