config/routes.rb
Rails.application.routes.draw do

  get 'classrooms/index'

  resources :sales, only: [:index, :new, :create]
  resources :exchanges
  resources :deposits
  resources :withdrawals

  resources :attachments, only: [:new, :create]

  resources :courses, except: [:index, :edit, :update, :destroy], :path => "cursos" do
    resources :subjects, except: [:destroy], :path => "materia" do
      resources :lessons, except: [:destroy], :path => "aula" do
        resources :quizzes, except: [:destroy], :path => "quiz" do
          resources :questions, except: [:destroy], :path => "questao"
        end
      end
    end
  end

  resources :classrooms
  resources :questions, except: [:destroy]
  resources :user_answers, only: [:new, :create]
  resources :transictions, only: [:new, :create, :index, :show]
  resources :users, only: [:new, :create, :index] do
    resources :wallets, only: [:show], :path => "carteira"
  end
  resources :test_classes, except: [:edit, :update, :destroy, :new, :index], :path => "aula-gratis"
  get "/aula-gratis", to: "test_classes#new"
  resources :contacts, except: [:edit, :update, :destroy], :path => "contato"
  resources :blogs, except: [:destroy], :path => "blog"
  resources :dashboards, only: [:index]
  resources :tutorials
  resources :enrollments
  devise_for :users, :path => "usuario", controllers: {sessions: "sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/home'
  get '/curso/:id', to: "courses#student_show", as: :student_show
  get '/rio-de-janeiro', to: "pages#rio_de_janeiro"
  get '/seja-um-franqueado', to: "pages#franchise"
  root to: 'pages#home'

end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  belongs_to :course

  mount_uploader :file, PhotoUploader
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]

  def index
    @tutorials = policy_scope(Tutorial).order(course_id: :asc)
    @colors = ['background-color: #373F51;','background-color: #ECB5D3;','background-color: #008DD5;', 'background-color: #7BE0AD;', 'background-color: #31081F;', 'background-color: #8A716A;']
    @set_color = []
    @courses = Course.all
    @courses.each_with_index do |course, index|
      @set_color << {course_id: course.id, course_color: index}
    end
    @enrollments = current_user.enrollments
    authorize Tutorial
    @tutorial = Tutorial.new
  end

  def new
    @tutorial = Tutorial.new
    authorize @tutorial
  end

  def show
    @tutorials = policy_scope(Tutorial).order(created_at: :asc)
    # before_action
    authorize @tutorial

  end

  def create
    @tutorial = Tutorial.new(tutorial_params)
    authorize @tutorial
    @tutorial.save
    redirect_to tutorials_path
  end

  def edit

    @tutorial = Tutorial.find(params[:id])
    authorize @tutorial
    respond_to do |format|
      format.html { render 'lessons/edit' }
      format.js  # <-- idem
    end
  end

  def update
    # before_action
    @tutorial.update(tutorial_params)
    redirect_to root_path
  end

  def destroy
    # before_action
    @tutorial.destroy
    redirect_to root_path
  end


  private

  def set_tutorial
    @tutorial = Tutorial.find(params[:id])
  end

  def tutorial_params
    params.require(:tutorial).permit(:course_id, :title, :subtitle, :video, :file)
  end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_index.html.erb
<section>
  <div class="row p-0 p-sm-4 bg-grey rounded mt-5">
    <div class="col-sm-12 text-center mb-5 mt-4 px-0 px-sm-5">
      <h4>Tutoriais</h4>
    </div>
    <div class="col-sm-12 ">
      <% count = 0 %>
      <% @tutorials.in_groups_of(3, false).each do |group| %>
        <div class="row text-center">

          <% group.each_with_index do |tutorial, index| %>
            <%= link_to tutorial_path(tutorial), remote: true do %>
              <% if tutorial.course_id == @set_color[count][:course_id] %>
                <% this_color = @set_color[count][:course_color] %>
              <% else %>
                <% count = count + 1 %>
                <% this_color = count %>
              <% end %>
              <div class="col-sm-4 px-0 px-sm-5">
                <div class="tutorial-card mb-5 blog-card pt-2" style="<%= @colors[this_color] %>">
                  <p class="my-2 text-white"><%= tutorial.title %></p>
                  <div class="horizontal-line"></div>
                  <p class="mb-0 p-2 p-link text-white"><%= link_to tutorial.course.title, tutorial_path(tutorial), remote: true %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <%= render "tutorials/new" %>
</section>

app/views/tutorials/_new.html.erb
<% if policy(@tutorial).new? %>
  <br>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h3 class="text-center">Cadastrar Tutorial</h3>
      <%= simple_form_for @tutorial, html: { class: "form-container"} do |f| %>
        <%= f.input :title, label: 'Tutorial', placeholder: 'Digite o título' %>
        <%= f.input :subtitle, label: 'Descrição', placeholder: 'Digite a descrição' %>
        <%= f.input :video, label: 'Url do video', placeholder: 'Digite a url do video' %>
        <label class="btn btn-warning mb-0">
          <i class="fas fa-image"></i>
          <span style="display: none;">
            <%= f.input :file %>
          </span>
        </label>
        <%= f.association :course, label: 'Curso', as: :radio_buttons %>
        <%= f.submit 'Criar tutorial', class: 'btn btn-info' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tutorials/_show.html.erb
<div class="row text-center">
  <div class="col-sm-12 px-0 px-sm-2">
    <div class="course-card mb-1 mb-sm-5">
      <p class="mt-3"><%= @tutorial.title %>
        <% if policy(Tutorial).edit? %>
          <%= link_to "[editar]", edit_tutorial_path(@tutorial), remote: true %></p>
        <% end %>
      <% if @tutorial.video? %>
        <% if @tutorial.video.include? 'vimeo' %>
          <iframe src="<%= @tutorial.video %>" width="100%" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        <% else %>
          <iframe width="100%" height="500" src="https://www.youtube.com/embed/<%=@tutorial.video.split('watch?v=').last if @tutorial.video %>" frameborder="0" allowfullscreen></iframe>
        <% end %>
      <% end %>
      <p class="my-2"><%= @tutorial.subtitle %></p>
      <br>
      <% if @tutorial.file.nil? == false %>
        <div>
          <object data="<%= cloudinary_url(@tutorial.file, :secure => true) %>" type="application/pdf" width="100%" height="500">
          </object>
          <a href="<%= @tutorial.file %>" download="" class="btn btn-primary"><i class="glyphicon glyphicon-cloud-download"></i> baixar material de apoio</a>
        </div>
      <% else %>
        <% if policy(@tutorial).edit? %>
          <div>
            <%= link_to "[adicionar slide]", edit_tutorial_path(@tutorial), remote: true %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tutorials/index.html.erb
<% content_for :sidebar do %>
  <div class="wrapper">
    <%= render 'shared/sidebar' %>
   <!-- Page Content -->
    <div id="content-bar">
      <nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between align-items-center">
        <button type="button" id="sidebarCollapse" class="btn btn-info">
          <i class="fas fa-align-left"></i>
        </button>
        <span class="dropdown-custom pl-3">
          <span class="btn btn-sm btn-outline-dark dropbtn" onclick="myFunction()">
            Meu perfil
          </span>
          <div id="myDropdown" class="dropdown-menu dropdown-content-custom dropdown-menu-right" style="min-width: 15rem;">
            <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: "px-4 py-3 form-group"}) do |f| %>
              <% if !user_signed_in? %>
                <div class="form-inputs">
                <%= f.input :email, required: false, autofocus: true, class: 'form-control', label: 'Login', placeholder: 'usuário ou email' %>
                <%= f.input :password, required: false, input_html: { autocomplete: "current-password" }, class: 'form-control', label: 'Senha', placeholder: 'senha' %>
                <%= f.input :remember_me, class: 'form-control', label: 'Lembrar senha', as: :boolean if devise_mapping.rememberable? %>
                </div>
              <% else %>
                <div class="form-inputs d-flex justify-content-between align-items-center mb-3">
                  <%= cl_image_tag(current_user.photo, class: 'avatar-mini') %>
                  <%= current_user.first_name %>
                </div>
                <div class="form-inputs">
                  <i class="fas fa-briefcase"></i>
                  <%= link_to "Dashboard", dashboards_path%>
                </div>
                <div class="form-inputs">
                  <i class="fas fa-user-edit"></i>
                  <%= link_to "Editar perfil", edit_user_registration_path(current_user)%>
                </div>
              <% end %>
              <div class="form-actions mt-3">
                <% if user_signed_in? %>
                  <%= link_to "Sair", destroy_user_session_path, class: 'btn btn-danger btn-block', method: :delete %>
                <% else %>
                  <%= f.button :submit, "Login", class: 'btn btn-primary btn-block' %>
                  <%= render "devise/shared/links" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </span>
      </nav>
      <section>
        <div class="container-fluid">
          <% if flash[:notice] %>
            <div class="alert alert-info alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= flash[:notice] %>
            </div>
          <% end %>
          <% if flash[:alert] %>
            <div class="alert alert-warning alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= flash[:alert] %>
            </div>
          <% end %>
          <div class="row p-0 p-sm-4">
            <div class="col-sm-12" id="ajax-content">
              <%= render "index" %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
<% end %>

app/views/tutorials/show.js.erb
// app/views/courses/create.js.erb
// Here you generate *JavaScript* that would be executed in the browser
function showCourse(courseHTML) {
  const courses = document.getElementById('ajax-content');
  $(courses).html(courseHTML);
}
showCourse('<%= j render "tutorials/show" %>');